title: TempFiles
permalink: pretty
author:
  name: "Carlgo11"
  url: "https://carlgo11.com/"
sass:
  sass_dir: css
  style: compressed
repository: carlgo11/tempfiles
exclude:
  - LICENSE
  - README.md
  - .*
  - Gemfile*
  - docker-compose.yml